# Generated by Django 4.1.7 on 2023-04-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LL84Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address_1', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=2)),
                ('postcode', models.CharField(max_length=5)),
                ('borough', models.CharField(max_length=50)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('property_name', models.CharField(max_length=100)),
                ('nyc_bbl', models.CharField(max_length=20)),
                ('nyc_bin', models.CharField(max_length=10)),
                ('primary_property_type_calculated', models.CharField(max_length=100)),
                ('primary_property_type_selected', models.CharField(max_length=100)),
                ('property_use_types', models.CharField(max_length=150)),
                ('year_built', models.CharField(max_length=4)),
                ('energy_star_score', models.IntegerField()),
                ('energy_star_years', models.CharField(max_length=100)),
                ('weather_normalized_energy_use', models.FloatField()),
                ('weather_normalized_electricity_use', models.FloatField()),
                ('weather_normalized_electricity_intensity', models.FloatField()),
                ('weather_normalized_natural_gas_use', models.FloatField()),
                ('weather_normalized_natural_gas_intensity', models.FloatField()),
                ('total_ghg_emissions', models.FloatField()),
                ('total_ghg_emissions_intensity', models.FloatField()),
                ('egrid_output_emissions_rate', models.FloatField()),
                ('leed_project_id', models.CharField(max_length=15)),
                ('gfa', models.IntegerField()),
                ('water_use', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BINLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nyc_bin', models.CharField(max_length=10)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ll84building')),
            ],
        ),
    ]
